# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://subversedialogue.github.io
type: git
repo: git@github.com:notcookies/subversedialogue.github.io.git
branch: main
